django_app/mystie/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # polls/일 경우, polls.urls을 호출
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

django_app/polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    # 아무것도 입력되지 않았을 경우, views.index 호출
    # ex: /polls/
    url(r'^$', views.index),

    # 숫자 1개 이상이면, views.detail 호출
    # 이때, question_id에 패턴을 넣어 넘겨준다.
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),

    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),

    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

django_app/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# 데이터베이스가 어떻게 만들어질지 정의
class Question(models.Model):
    q_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.q_text

    def was_published_recently(self):
        """
        최근에 발행된 Question 인가 판단해주는 메서드
        :return: Boolean
        """
        # 자신의 발행일자 >= 현재시각 - 하루만큼의 시간간
        # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question)
    c_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.c_text

django_app/mystie/views.py
"""
루트 URL(r'^$')에
polls/와 admin/으로 갈 수 있는 링크 페이지를 구현한다

1. 뷰는 mysite/views/py 안에 def index(request)에 작성
2. 템플릿은 templates/index.html을 사용
    polls/, admin/ 연결하는 부분은 {% url %} 태그 쓰지 않고 직접 구현
3. URL은 mystie/urls.py에
"""
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

django_app/polls/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.utils.datastructures import MultiValueDictKeyError

from .models import Question, Choice


def index(request):
    # pub_date 컬럼(필드)를 기준으로 내림차순 정렬(-pub_date, 마이너스)한 결과를 latest_question_list에 할당
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


    # 템플릿으로 분리 (원리)
    # # 템플릿 loader를 이용해서 'polls/index.html'에서 템플릿을 가져옴
    # template = loader.get_template('polls/index.html')
    #
    # # 템플릿 파일에 전달할 context 객체를 정의
    # # 'latest_question_list' 키에 값을 할당
    # # 해당 키를 템플릿에서 사용
    # context = {'latest_question_list': latest_question_list, }
    #
    # # 템플릿에 context와 request 객체를 사용해 render한 결과를 반환
    # return HttpResponse(template.render(context, request))

    # 뷰를 직접구현
    # output = ', '.join([q.q_text for q in latest_question_list])
    # # 디버그 테스트
    # # request 객체 확인해보기
    # # request는 사용자가 요청할 때 담아보내는
    # output2 = ''
    # for q in latest_question_list:
    #     output2 += q.q_text + ', '
    # output2 = output2[:-2]
    #
    # return HttpResponse(output2)


def detail(request, question_id):
    """
    request.method == 'POST'일 때, 전달받은 POST객체에서
        'choice' 키 값을 HttpResponse로 되돌려준다.
        'choice' 키로 전달된 Choice 객체의 id를 이용해서
        해당 Choice 객체의 votes 값을 1 늘려주고 데이터베이스 업데이트
        완료되면 다시 Question detail 페이지로 이동

        1. request.Post['choice']의 값(Choice객체의 ID)을 이용해서 Choice 객체를 가져온다
        2. 해당 객체의 votes 값을 늘려주고, 데이터베이스에 변경사항을 업데이트
        3. redirect, question_id를 이용해서 detail 페이지로 다시 돌아간다
    아닐 경우 polls/detail.html을 render
    """
    if request.method == 'POST':
        # 1번
        try:
            choice_id = request.POST['choice']
            choice = Choice.objects.get(id=choice_id)

        except MultiValueDictKeyError:
            return HttpResponse('test')

        # 2번번
        choice.votes += 1
        choice.save()

        # 3번
        return redirect('polls:results', question_id=question_id)

    else:
        question = Question.objects.get(id=question_id)
        context = {
            'question': question,
        }
        return render(request, 'polls/detail.html', context)


def results(request, question_id):
    # 인자로 주어진 question_id에 해당하는 Question 객체를 context에 담아 render에 보낸다
    question = Question.objects.get(id=question_id)
    context = {
        'question': question,
    }
    return render(request, 'polls/results.html', context)




def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

django_app/templates/index.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django tutorial Main</title>
</head>
<body>
    <h1>Django Tutorial</h1>
    <ul>
        <li><a href="/polls/">Polls application</a></li>
        <li><a href="/admin/">Django admin page 이동</a></li>
    </ul>
</body>
</html>

django_app/templates/polls/detail.html
<h1>{{ question.q_text }}</h1>
<form action="" method="POST">{% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input
            type="radio"
            name="choice"
            value="{{ choice.id }}">
    <label for="">{{ choice.c_text }}</label>
    {% endfor %}
    <button type="submit">Vote</button>
</form>

django_app/templates/polls/index.html
<!-- 템플릿 언어, 쿼리를 사용할 수 있음 -->
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question_id=question.id %}">{{ question.q_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

django_app/templates/polls/results.html
<h1>{{ question.q_text}} Result</h1>
<!--
아래 루프를 돌면서 해당 choice의 c_text의 votes 값 출력
-->

{% for choice in question.choice_set.all %}
<div>
    {{ choice.c_text }} : {{ choice.votes }}
</div>

{% endfor %}